version: '3'

services:
  moodle:
    build: ./docker/moodle
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./siteroot:/siteroot
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes:
      - 'db:/var/lib/postgresql'
  moodle-integration-db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_integration
      POSTGRES_USER: dev_integration
    volumes:
      - 'moodle-integration-db:/var/lib/postgresql'
  test-db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes:
      - 'testdb:/var/lib/postgresql'
volumes:
    db:
    moodle-integration-db:
    testdb: